"""Classify a FedRAMP assessment-tracker row into a structured evidence-gap type.

The assessor's evidence-request rows in a FedRAMP tracker are heterogeneous human-written
prose. This module turns each row into one of the canonical :class:`core.models.GapType`
values plus, where possible, a recommended artifact and a recommended validation step.

The classifier is **deterministic** and **substring-keyword-based**. It does not invent
evidence; it only labels what the assessor asked for. It is intentionally separate from
the surrounding category-classifier in :mod:`normalization.assessment_tracker_import`
(which buckets a row into ``inventory`` / ``scanner`` / ``logging`` / etc. for fixture
file routing). Here we go finer-grained: a row already classified as ``scanner`` could
become ``scanner_scope_missing``, ``vulnerability_scan_evidence_missing``, or
``credentialed_scan_evidence_missing`` depending on the precise wording.
"""

from __future__ import annotations

import re
from dataclasses import dataclass

from core.models import GapSeverity, GapType


__all__ = [
    "GapClassification",
    "classify_tracker_gap",
    "PHRASE_RULES",
]


@dataclass(frozen=True)
class GapClassification:
    """Result of classifying a tracker row."""

    gap_type: GapType
    severity: GapSeverity
    recommended_artifact: str | None
    recommended_validation: str | None
    matched_phrases: list[str]
    poam_required: bool


# ---------------------------------------------------------------------------
# Phrase rules — ORDER MATTERS. More specific rules must come before broader ones.
# Each entry: (gap_type, severity, recommended_artifact, recommended_validation, phrases)
# ---------------------------------------------------------------------------

_RECOMMENDED_ARTIFACTS: dict[GapType, str] = {
    "inventory_mismatch": "declared_inventory.csv reconciled against discovered_assets.json",
    "scanner_scope_missing": "scanner_targets.csv covering every in-boundary asset",
    "vulnerability_scan_evidence_missing": "scanner_findings.json export from latest credentialed scan",
    "credentialed_scan_evidence_missing": "scanner_targets.csv with credentialed=true + plugin/profile evidence",
    "centralized_log_missing": "central_log_sources.json showing source -> SIEM ingestion",
    "local_to_central_log_correlation_missing": (
        "central_log_sources.json plus a local audit log sample correlated with the central index"
    ),
    "alert_rule_missing": "alert_rules.json entry with controls + recipients",
    "alert_sample_missing": "sample_alert_ref pointing at an executed alert export",
    "response_action_missing": "tickets.json entry citing the alert with documented response",
    "change_ticket_missing": "tickets.json entry linking change request to deployed assets",
    "sia_missing": "tickets.json field security_impact_analysis=true with SIA attachment",
    "testing_evidence_missing": "tickets.json field test_evidence=true with test artifacts",
    "approval_missing": "tickets.json field approval_recorded=true with CAB minutes",
    "deployment_evidence_missing": "tickets.json field has_deployment_evidence=true with deploy log",
    "verification_evidence_missing": "tickets.json field has_verification_evidence=true with post-deploy proof",
    "exploitation_review_missing": (
        "scanner_findings.json finding with exploitation_review.queries[] + log_review_performed=true"
    ),
    "poam_update_missing": "poam.csv with current status, dates, and milestones",
    "deviation_request_missing": "poam.csv row with deviation_request_ref + approval evidence",
    "backup_evidence_missing": "backup_assets.json + most-recent backup execution log",
    "restore_test_missing": "restore_tests.json with measured RTO/RPO",
    "identity_listing_missing": "identity_users.json + privileged-account flag + MFA report",
    "password_policy_evidence_missing": "password policy export + IdP enforcement evidence",
    "crypto_fips_evidence_missing": "FIPS 140-2/3 module list + KMS rotation export + cipher policy",
    "traffic_flow_policy_missing": "data-flow diagram + security_group inventory + ports/protocols matrix",
    "unknown": None,  # type: ignore[dict-item]
}

_RECOMMENDED_VALIDATIONS: dict[GapType, str] = {
    "inventory_mismatch": "Run CM8_INVENTORY_RECONCILIATION on the produced CSV+JSON",
    "scanner_scope_missing": "Run RA5_SCANNER_SCOPE_COVERAGE",
    "vulnerability_scan_evidence_missing": "Re-import via `import-findings --format prowler|ocsf`",
    "credentialed_scan_evidence_missing": "Verify scanner_targets.credentialed flag in RA5_SCANNER_SCOPE_COVERAGE",
    "centralized_log_missing": "Run AU6_CENTRALIZED_LOG_COVERAGE",
    "local_to_central_log_correlation_missing": (
        "AU6_CENTRALIZED_LOG_COVERAGE local-vs-central correlation must show seen_last_24h=true"
    ),
    "alert_rule_missing": "Run SI4_ALERT_INSTRUMENTATION",
    "alert_sample_missing": "SI4_ALERT_INSTRUMENTATION requires sample_alert_ref to be non-empty",
    "response_action_missing": "Run CROSS_DOMAIN_EVENT_CORRELATION (alert -> ticket linkage)",
    "change_ticket_missing": "Run CM3_CHANGE_EVIDENCE_LINKAGE",
    "sia_missing": "CM3_CHANGE_EVIDENCE_LINKAGE expects security_impact_analysis=true",
    "testing_evidence_missing": "CM3_CHANGE_EVIDENCE_LINKAGE expects test_evidence=true",
    "approval_missing": "CM3_CHANGE_EVIDENCE_LINKAGE expects approval_recorded=true",
    "deployment_evidence_missing": "CM3_CHANGE_EVIDENCE_LINKAGE expects has_deployment_evidence=true",
    "verification_evidence_missing": "CM3_CHANGE_EVIDENCE_LINKAGE expects has_verification_evidence=true",
    "exploitation_review_missing": "Run RA5_EXPLOITATION_REVIEW",
    "poam_update_missing": "Run CA5_POAM_STATUS",
    "deviation_request_missing": "Validate poam.csv deviation columns then re-run CA5_POAM_STATUS",
    "backup_evidence_missing": "Validate backup_assets.json shape (no automated eval yet — manual review)",
    "restore_test_missing": "Validate restore_tests.json + measured RTO/RPO (manual review)",
    "identity_listing_missing": "Run AGENT_PERMISSION_SCOPE / IAM review (manual + automated)",
    "password_policy_evidence_missing": "Verify IdP password policy export (manual review)",
    "crypto_fips_evidence_missing": "Verify FIPS module list + KMS rotation (manual review)",
    "traffic_flow_policy_missing": "Validate SG inventory + DFD against authorization-scope.yaml",
    "unknown": None,  # type: ignore[dict-item]
}

# Each rule: (gap_type, severity, *phrases). Order = priority (first match wins).
_GAP_RULES: tuple[tuple[GapType, GapSeverity, tuple[str, ...]], ...] = (
    # Pen-test / perimeter scope rows (before broad inventory "iiw" matches assessor side-mentions)
    (
        "traffic_flow_policy_missing",
        "high",
        (
            "publicly facing ip",
            "publicly facing",
            "pen test scope",
            "penetration test scope",
            "ports/protocols matrix",
            "customer responsibility matrix",
            "functions ports and services",
            "interconnection",
        ),
    ),
    # ----- inventory --------------------------------------------------------
    (
        "inventory_mismatch",
        "high",
        (
            "inventory appears to be evolving",
            "discrepancies",
            "discrepancies.",
            "stale cmdb",
            "stale entries",
            "orphan",
            "orphaned entries",
            "reconcile declared",
            "reconcile inventory",
            "integrated inventory workbook",
            "iiw",
            "compared the inventory",
            "did not exist in the",
            "duplicate entries",
            "unique identifier",
            "aws dump",
            "aws account dump",
            "trendmicro inventory",
            "system component inventory",
            "inventory of load balancers",
            "inventory of s3",
            "load balancer inventory",
            "ec2 inventory",
            "rds inventory",
            "vpc inventory",
            "s3 inventory",
            "alb/nlb inventory",
            "ip ranges",
            "ip allocation",
            "subnet listing",
            "asset inventory",
            "sbom",
            "cyclonedx",
            "spdx",
            "software bill of materials",
            "machine-readable sbom",
        ),
    ),
    # ----- scanner: most specific first -------------------------------------
    (
        "credentialed_scan_evidence_missing",
        "high",
        (
            "credentialed checks",
            "credentialed scan",
            "credentialed administrator",
            "authenticated scan",
            "privileged access",
            "privileged scan",
            "credentialed-scan",
            "database vulnerability scans",
            "ra-5(5)",
            "authenticated vulnerability scan",
            "authenticated vulnerability scan reports",
        ),
    ),
    # Witness / observe scheduling (must precede broad "plugins"/vuln scan rules)
    (
        "scanner_scope_missing",
        "high",
        (
            "3pao to witness",
            "witness of vulnerability",
            "witness full scan",
            "witness of scan",
            "assessor witness",
            "observe scan",
            "observe the scan",
            "observe performance of scans",
        ),
    ),
    (
        "vulnerability_scan_evidence_missing",
        "high",
        (
            "plugins",
            "updated prior to each new scan",
            "vulnerability scan reports",
            "vulnerability scan report",
            "scan plugins",
            "scan signatures",
            "burp signatures",
            "burp suite",
            "nessus vulnerability scan",
            "scan tool version",
            "scanner tools and their installed version",
            "listing of vulnerability scanning tools",
            "recurring vulnerability scan",
            "scan frequency",
            "ra-5(2)",
        ),
    ),
    (
        "scanner_scope_missing",
        "high",
        (
            "provide evidence to display all system components that are scanned",
            "all system components that are scanned",
            "scan target list",
            "scan scope",
            "scanner scope",
            "in-boundary assets in scope",
            "in scope for scanning",
            "scanner_targets",
        ),
    ),
    # ----- exploitation review ---------------------------------------------
    (
        "exploitation_review_missing",
        "critical",
        (
            "historic audit logs",
            "historical audit log",
            "historical audit logs",
            "evidence of exploitation",
            "exploitation review",
            "exploit review",
            "ioc",
            "indicator of compromise",
            "high/critical vulnerabilities open",
            "critical vulnerabilities open",
            "compromise assessment",
        ),
    ),
    # Specific mail/phishing sample rows before broad "log retention" / SIEM logging matches.
    (
        "alert_sample_missing",
        "high",
        (
            "spam filter evidence",
            "spam protection evidence",
            "phishing email filtered",
            "phishing message filtered",
            "filtered phishing email",
            "mail security log",
            "mail gateway log",
        ),
    ),
    # ----- logging ----------------------------------------------------------
    (
        "local_to_central_log_correlation_missing",
        "high",
        (
            "local audit log",
            "local log",
            "local auth",
            "same audit log contained within splunk",
            "same event",
            "identical audit",
            "centralized siem",
            "matches centralized",
            "correlate local",
            "local-to-central",
            "forwarder healthcheck",
            "forwarder healthchecks",
            "forwarder healthy",
        ),
    ),
    (
        "centralized_log_missing",
        "high",
        (
            "centralized audit log aggregation",
            "central log aggregation",
            "centralized log",
            "central log",
            "centralized audit log",
            "log aggregation",
            "siem onboarding",
            "log forwarding",
            "log forwarder",
            "ingestion stale",
            "vpc flow log",
            "vpc flow logs",
            "cloudwatch logs",
            "immutable bucket",
            "object lock",
            "append-only",
            "audit trail",
            "worm-style",
            "au-3",
            "audit record content",
            "audit field mapping",
            "au-9",
            "audit information protection",
            "protection of audit",
            "audit log protection",
            "au-11",
            "audit retention",
            "log retention",
            "au-4",
            "audit event frequency",
            "audit events generated",
            "au-2",
            "auditable events",
            "audit events baseline",
            "au-13",
            "unauthorized disclosure of audit",
            "audit information disclosure",
            "monitoring for audit",
            "au-8",
            "time synchronization",
            "clock skew",
            "ntp",
            "stratum-1",
        ),
    ),
    # ----- alerting / response ---------------------------------------------
    (
        "alert_sample_missing",
        "high",
        (
            "example alerts",
            "example alert that fired",
            "example alert email",
            "sample alert",
            "alert export",
            "saved search export",
            "soc email notification",
            "spam filter evidence",
            "spam protection evidence",
            "phishing email filtered",
            "phishing message filtered",
            "filtered phishing email",
            "mail security log",
            "mail gateway log",
        ),
    ),
    (
        "response_action_missing",
        "high",
        (
            "actions taken in response",
            "documented response action",
            "response action",
            "incident handling actions",
            "incident response evidence",
            "incident response",
            "incident ticket",
            "incident report",
            "us-cert",
            "cisa report",
            "cisa notification",
            "incident closure",
            "suspected incident",
            "confirmed incident",
            "security incidents",
            "suspected and confirmed",
            "externally reported",
            "threat hunt",
            "threat hunting",
            "active defense",
            "hunt program",
            "hunt report",
            "ir-4",
            "ir-9",
            "information spillage",
            "data spillage",
            "spillage handling",
        ),
    ),
    (
        "alert_rule_missing",
        "high",
        (
            "enabled alerts",
            "alert rules",
            "alert rule",
            "alerting",
            "recipient list",
            "alert recipient",
            "notification recipient",
            "guardduty notifications",
            "cloudwatch alarms",
            "cloudwatch alarm",
            "alert configuration",
            "alert dashboard",
            "saved search",
            "heightened monitoring",
            "heightened posture",
            "increased risk",
            "extended log review",
            "file integrity monitoring",
            "integrity monitoring configuration",
            "fim policy",
            "monitored paths",
            "si-7",
            "application integrity monitoring",
            "malware detection",
            "malware protection",
            "anti-malware",
            "sc-34",
            "denial of service",
            "denial-of-service",
            "dos monitoring",
            "syn flood",
            "volumetric threshold",
            "si-4(23)",
            "host-based intrusion",
            "host intrusion detection",
            "host-based security",
            "si-5",
            "security warning banner",
            "security warning",
        ),
    ),
    # Restore / DR exercises (before CM testing chain — avoid "lessons learned" stealing CP rows)
    (
        "restore_test_missing",
        "high",
        (
            "annual restore",
            "restore exercise",
            "measured rto",
            "measured rpo",
            "rto and rpo",
            "recovery test",
            "dr exercise",
            "dr ticket",
            "restore test",
            "rto/rpo",
        ),
    ),
    # ----- change evidence chain (most specific first) ---------------------
    (
        "sia_missing",
        "high",
        (
            "sia",
            "security impact analysis",
            "sia performed before deployment",
            "no sia",
            "lacks security impact analysis",
            "lacks a security impact analysis",
            "no security impact analysis",
            "significant change form",
            "significant change forms",
            "significant change request",
            "scr package",
            "scr approval",
            "security impact determination",
        ),
    ),
    (
        "testing_evidence_missing",
        "moderate",
        (
            "test documentation",
            "test evidence",
            "testing evidence",
            "testing artifacts",
            "test artifacts",
            "test records",
            "no test evidence",
            "test results report",
            "lessons learned",
            "tabletop",
            "functional test",
            "contingency plan excerpt",
            "alternate processing site",
            "alternate processing",
            "continuity of operations",
            "contingency training",
            "media sanitization",
            "sanitization equipment",
            "static analysis",
            "static application security",
            "sast",
            "security risk assessment",
            "organizational risk assessment",
            "risk assessment report",
            "ra-3",
            "ca-2",
            "security control assessment",
            "control assessment",
            "continuous monitoring strategy",
            "continuous monitoring",
            "ca-7",
            "ongoing assessment",
            "mp-5",
            "media transport",
            "chain of custody",
            "removable media",
            "si-10",
            "input validation",
            "malformed payload",
            "error handling test",
            "cm-6",
            "configuration baseline",
            "baseline configuration",
            "baseline inventory",
            "si-11",
            "fault injection",
            "failure recovery",
            "sa-21",
            "developer environment",
            "development environment",
            "sc-39",
            "process isolation",
            "ir-8",
            "si-12",
            "secure development lifecycle",
            "sdlc",
            "sa-4",
            "acquisition security",
            "si-16",
            "memory protection",
            "address space layout",
            "aslr",
            "sc-23",
            "fail secure",
            "fail-secure",
            "fail to a known state",
            "cm-3(2)",
            "non-production environment",
            "production parity",
            "test environment parity",
            "si-14",
            "non-persistence",
            "transient storage",
            "ephemeral compute",
            "volume wipe",
            "sc-51",
            "trusted platform module",
            "tpm",
            "tpm quote",
            "pcr bank",
            "si-18",
            "mobile code",
            "active content",
            "content security policy",
            "content-security-policy",
            "si-17",
            "fail-safe",
            "fail safe",
            "degraded mode",
            "si-19",
            "voice and video",
            "collaboration session",
            "voip security",
            "unified communications",
            "media encryption",
            "pm-9",
            "risk executive function",
            "authorizing official",
            "cp-10",
            "alternate communications",
            "crisis bridge",
            "sa-11",
            "application security testing",
            "pipeline security",
            "dynamic application security",
            "cm-7",
            "least functionality",
            "disabled listening",
            "disabled services",
            "ra-9",
            "criticality analysis",
            "impact category",
            "scoring rubric",
            "cp-8",
            "alternate telecommunications",
            "telecommunications service",
        ),
    ),
    (
        "approval_missing",
        "moderate",
        (
            "approval evidence",
            "cab approval",
            "no approval",
            "missing approval",
            "change advisory board",
            "approval recorded",
            "approval export",
            "electronic approval",
            "evidence of review and approval",
            "review and approval of",
            "review and approval",
            "has been reviewed and approved",
            "approved by",
            "notified of most recent updates",
            "sample email and automatic notification",
            "manner in which personnel were notified",
            "sample notification email",
            "notification email",
            "prior to posting",
            "publicly accessible",
            "public-facing content",
            "web content review",
            "reviewed before posting",
            "log review sign-off",
            "privileged activity log review",
            "periodic log review",
            "ac-3(4)",
            "dual authorization",
            "two-person rule",
            "two-person control",
            "maker-checker",
            "maker checker",
        ),
    ),
    (
        "deployment_evidence_missing",
        "moderate",
        (
            "deployment evidence",
            "deploy evidence",
            "deployment log",
            "no deployment evidence",
            "missing deployment",
            "production deployment",
            "prior to production deployment",
            "artifact digest",
            "build digest",
            "attestation",
            "signature bundle",
            "in-toto",
            "cryptographically verified",
        ),
    ),
    (
        "verification_evidence_missing",
        "moderate",
        (
            "verification evidence",
            "post-deploy verification",
            "post-deploy",
            "no verification",
            "missing verification",
        ),
    ),
    (
        "change_ticket_missing",
        "high",
        (
            "change ticket",
            "change tickets",
            "change request",
            "rfc ticket",
            "jira",
            "no change ticket",
            "missing change ticket",
            "ccb meeting",
            "change control board",
            "ccb minutes",
            "si-2",
            "flaw remediation",
            "patch ticket",
            "remediation ticket",
            "security patch",
        ),
    ),
    # ----- POA&M / deviation (POA&M *updates* before vendor-dependency-only asks) ---
        (
            "poam_update_missing",
            "moderate",
            (
                "poa&m updated",
                "poa&m update",
                "poa&m updates",
                "poam updated",
                "poam updates",
                "poa&m was updated",
                "plan of action and milestones was updated",
                "milestones was updated",
                "sar appendix poa&m",
                "sar appendix",
                "poa&m export",
                "poa&m csv",
                "official poa&m",
            ),
        ),
        (
            "deviation_request_missing",
            "moderate",
            (
                "deviation request",
                "false positive request",
                "risk acceptance request",
                "vendor dependency",
                "operational requirement",
                "fedramp deviation",
                "false positive",
                "risk adjustment",
                "supply chain risk reassessment",
                "supply chain risk",
                "software supply chain",
                "subprocessor",
                "flow-down",
                "fedramp authorization id",
                "fedramp authorization",
                "control inheritance",
                "inheritance memo",
                "leveraged fedramp",
                "sa-15",
                "processor agreement",
                "subprocessor oversight",
            ),
        ),
    # ----- backup / recovery -----------------------------------------------
        (
            "backup_evidence_missing",
            "moderate",
            (
                "backup evidence",
                "snapshot evidence",
                "database snapshots",
                "ami backup",
                "ami snapshot",
                "ami creation",
                "rds snapshot",
                "backup execution log",
                "snapshots are encrypted",
                "customer-managed kms",
                "offline backup",
                "contingency plan",
                "emergency roster",
                "backup scope",
                "cp-6",
                "alternate storage site",
                "alternate storage",
            ),
        ),
    # ----- IAM / identity --------------------------------------------------
    (
        "password_policy_evidence_missing",
        "moderate",
        (
            "password policy",
            "ia-5",
            "complexity policy",
            "minimum password length",
            "ac-7",
            "account lockout",
            "lockout threshold",
            "unsuccessful logon",
            "failed logon",
            "ac-10",
            "concurrent session",
            "session limit",
            "concurrent login",
        ),
    ),
    (
        "identity_listing_missing",
        "high",
        (
            "iam user list",
            "iam user listing",
            "account listing",
            "user listing",
            "privileged account",
            "service account inventory",
            "mfa report",
            "access review",
            "least privilege review",
            "iam role inventory",
            "employee roster",
            "personnel roster",
            "contractor roster",
            "terminated/off-boarded",
            "off-boarded",
            "exit interview",
            "security awareness training",
            "awareness training",
            "training completion",
            "phishing-resistance",
            "role-based security training",
            "role based training",
            "third-party",
            "third party",
            "personnel security compliance",
            "vendor review",
            "visitor access",
            "visitor log",
            "data center",
            "escort",
            "escorted access",
            "physical access report",
            "rules of behavior",
            "rule of behavior",
            "pl-4",
            "acceptable use",
            "acceptable use policy",
            "acknowledgement",
            "acknowledgment",
            "ac-3",
            "access enforcement",
            "logical access enforcement",
            "ac-6",
            "least privilege attestation",
            "privilege recertification",
            "least privilege recertification",
            "least-privilege recertification",
            "privilege reviews",
            "ac-21",
            "collaborative computing",
            "collaborative computing device",
            "conference room",
            "video conference",
            "ia-8",
            "identifier reuse",
            "authenticator issuance",
            "authenticator decommission",
            "decommissioned device",
            "ac-19",
            "mobile device",
            "portable computing",
            "mdm compliance",
            "mdm",
            "byod",
            "bring your own device",
            "ac-5",
            "separation of duties",
            "separation-of-duties",
            "segregation of duties",
            "sod matrix",
            "at-2",
            "phishing simulation",
            "security literacy",
        ),
    ),
    # ----- crypto / FIPS ---------------------------------------------------
    (
        "crypto_fips_evidence_missing",
        "high",
        (
            "fips 140",
            "fips-140",
            "fips validated",
            "fips validation",
            "crypto module",
            "kms key rotation",
            "key rotation",
            "cipher list",
            "tls cipher",
            "encryption at rest",
            "encryption in transit",
            "certificate inventory",
            "sc-13",
            "cryptographic key management",
            "key management policy",
            "key custodian",
            "key lifecycle",
            "sc-28",
            "user data at rest",
            "sc-12",
            "piv card",
            "piv credential",
            "derived credential",
            "smart card authenticator",
            "key establishment",
            "sc-8",
            "transmission confidentiality",
            "enforced tls",
            "cipher suite",
        ),
    ),
    # ----- traffic / boundary ----------------------------------------------
    (
        "traffic_flow_policy_missing",
        "high",
        (
            "traffic flow",
            "data flow diagram",
            "security group inventory",
            "security group",
            "ingress rule",
            "egress rule",
            "ports and protocols",
            "ports-and-protocols",
            "boundary diagram",
            "0.0.0.0/0",
            "administrative ports",
            "ports/protocols",
            "network segmentation",
            "segmentation diagram",
            "sc-7",
            "pl-8",
            "security architecture",
            "architecture roadmap",
            "ac-17",
            "remote access",
            "vpn concentrator",
            "vpn gateway",
            "split-tunnel",
            "ac-20",
            "distributed processing",
            "external compute",
            "si-15",
            "information exchange",
            "guarded information exchange",
            "ac-4",
            "approved information flows",
            "information flow enforcement",
            "sc-36",
            "processing site security",
            "distributed processing site",
            "sc-5",
            "connection rate limit",
            "rate limiting policy",
            "per-source quota",
            "resource quota",
        ),
    ),
)


PHRASE_RULES: tuple[tuple[GapType, GapSeverity, tuple[str, ...]], ...] = _GAP_RULES


# ---------------------------------------------------------------------------
# POA&M-required heuristic
# ---------------------------------------------------------------------------

# These gap types ALWAYS require a POA&M row when they remain open at acceptance.
_POAM_REQUIRED_TYPES: frozenset[GapType] = frozenset(
    {
        "exploitation_review_missing",
        "poam_update_missing",
        "deviation_request_missing",
        "scanner_scope_missing",
        "vulnerability_scan_evidence_missing",
        "credentialed_scan_evidence_missing",
        "centralized_log_missing",
        "local_to_central_log_correlation_missing",
        "alert_rule_missing",
        "alert_sample_missing",
        "response_action_missing",
        "change_ticket_missing",
        "sia_missing",
        "approval_missing",
        "deployment_evidence_missing",
        "verification_evidence_missing",
        "restore_test_missing",
    }
)

_HIGH_RISK_CONTROL_PATTERNS = (
    re.compile(r"\bRA-5\(8\)"),
    re.compile(r"\bAU-12\b"),
    re.compile(r"\bSI-4\(4\)"),
    re.compile(r"\bAC-2\(7\)"),
    re.compile(r"\bIR-4\(3\)"),
    re.compile(r"\bCP-9\b"),
)


def _bump_severity_for_controls(controls: list[str], severity: GapSeverity) -> GapSeverity:
    blob = " ".join(controls)
    if any(p.search(blob) for p in _HIGH_RISK_CONTROL_PATTERNS) and severity == "moderate":
        return "high"
    return severity


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def classify_tracker_gap(
    *,
    request_text: str,
    assessor_comment: str | None = None,
    csp_comment: str | None = None,
    controls: list[str] | None = None,
) -> GapClassification:
    """Return the structured :class:`GapClassification` for a tracker row's text.

    Concatenates ``request_text`` + ``assessor_comment`` + ``csp_comment`` and matches
    against :data:`_GAP_RULES` in order. First-match wins. Falls back to ``unknown``
    when no rule fires (the orchestrator decides what to do with that — typically
    creates an :class:`InformationalTrackerItem` rather than an :class:`EvidenceGap`).
    """
    haystack = " ".join(filter(None, [request_text, assessor_comment, csp_comment])).lower().strip()
    if not haystack:
        return GapClassification(
            gap_type="unknown",
            severity="low",
            recommended_artifact=None,
            recommended_validation=None,
            matched_phrases=[],
            poam_required=False,
        )

    for gap_type, severity, phrases in _GAP_RULES:
        matched = [p for p in phrases if p in haystack]
        if matched:
            sev = _bump_severity_for_controls(controls or [], severity)
            return GapClassification(
                gap_type=gap_type,
                severity=sev,
                recommended_artifact=_RECOMMENDED_ARTIFACTS.get(gap_type),
                recommended_validation=_RECOMMENDED_VALIDATIONS.get(gap_type),
                matched_phrases=matched,
                poam_required=gap_type in _POAM_REQUIRED_TYPES,
            )

    return GapClassification(
        gap_type="unknown",
        severity="low",
        recommended_artifact=None,
        recommended_validation=None,
        matched_phrases=[],
        poam_required=False,
    )
