#!/usr/bin/env python3
"""Evaluate evidence gaps as a virtual 3PAO using the LLM Reasoning Engine."""

import argparse
import json
import logging
import sys
from pathlib import Path

# Add project root to sys.path
ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from ai.reasoning import evaluate_3pao_remediation_for_gap, is_llm_configured


def main() -> int:
    parser = argparse.ArgumentParser(description="Evaluate evidence gaps as a virtual 3PAO.")
    parser.add_argument("--input", required=True, help="Path to evidence_gaps.json")
    parser.add_argument("--output", required=True, help="Path to write 3pao_remediation_report.md")
    parser.add_argument(
        "--related-artifacts",
        action="append",
        default=[],
        help=(
            "Optional JSON artifact to include in the reasonable-test sufficiency review. "
            "May be supplied multiple times."
        ),
    )
    args = parser.parse_args()

    input_path = Path(args.input).resolve()
    output_path = Path(args.output).resolve()

    if not input_path.is_file():
        print(f"Error: input file not found: {input_path}", file=sys.stderr)
        return 1

    try:
        envelope = json.loads(input_path.read_text(encoding="utf-8"))
    except Exception as e:
        print(f"Error reading JSON from {input_path}: {e}", file=sys.stderr)
        return 1

    raw_gaps = envelope.get("evidence_gaps") or envelope.get("gaps") or []
    if not raw_gaps:
        print("No evidence gaps found in input.", file=sys.stderr)
        return 0

    related_artifacts = {}
    for artifact_arg in args.related_artifacts:
        artifact_path = Path(artifact_arg).resolve()
        try:
            related_artifacts[artifact_path.name] = json.loads(
                artifact_path.read_text(encoding="utf-8")
            )
        except Exception as e:
            print(f"Error reading related artifact {artifact_path}: {e}", file=sys.stderr)
            return 1

    if not is_llm_configured():
        print("WARNING: AI_API_KEY is not configured. Falling back to deterministic mode.", file=sys.stderr)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    
    print(f"Evaluating {len(raw_gaps)} gap(s) as virtual 3PAO...")
    
    md_lines = [
        "# 3PAO Virtual Remediation Report",
        "",
        "The following recommendations and remediation plans were generated by applying the **'reasonable test'** to open evidence gaps.",
        ""
    ]

    count = 0
    for gap in raw_gaps:
        count += 1
        gap_id = gap.get("gap_id", "unknown")
        severity = gap.get("severity", "unknown")
        
        # We only really want to run 3PAO logic on open gaps, typically high/critical
        # but let's do it for all provided in the gaps list for thoroughness.
        print(f"[{count}/{len(raw_gaps)}] Analyzing {gap_id} (Severity: {severity})...")
        
        evaluation = evaluate_3pao_remediation_for_gap(
            evidence_gap=gap,
            related_artifacts=related_artifacts or None,
        )
        
        test_passed = "PASS" if evaluation.reasonable_test_passed else "FAIL"
        
        md_lines.extend([
            f"## Gap `{evaluation.gap_id}`",
            "",
            f"**Reasonable Test Result:** `{test_passed}`",
            "",
            "### Recommendation",
            evaluation.recommendation,
            "",
            "### Artifact Sufficiency",
            *[
                f"- **{item.status.upper()}** {item.requirement}: {item.evidence}"
                + (f" Remediation: {item.remediation}" if item.remediation else "")
                for item in evaluation.artifact_sufficiency
            ],
            "",
            "### Remediation Plan",
            evaluation.remediation_plan_md,
            ""
        ])

    output_path.write_text("\n".join(md_lines) + "\n", encoding="utf-8")
    print(f"\nWrote 3PAO Remediation Report to: {output_path}")

    return 0

if __name__ == "__main__":
    logging.basicConfig(level=logging.WARNING)
    sys.exit(main())
